# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb, "2000"]
    -   id: no-commit-to-branch
        args: [--branch, main]

-   repo: https://github.com/psf/black
    rev: 21.5b0
    hooks:
        - id: black
          args: [--line-length, "79"]

-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        args: [--profile, black]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
    -   id: flake8
        args: [--max-line-length, "79", --ignore, E402, --max-complexity, "10", --max-complexity, "7"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
