
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black isort flake8 mypy pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check code format with black
      run: black --check --diff --line-length 79 .
    - name: Check the order of import
      run: isort --check --diff --profile black .
    - name: Lint with flake8
      run: |
        flake8 --max-line-length 79 --ignore E402 --max-complexity 10 --max-complexity 7 .
    - name: Check type annotation with mypy
      run: mypy --ignore-missing-imports .
    - name: Test with pytest
      run: |
        pip install -e .
        cd tests
        pytest -v .
    - name: Debug
      if: ${{ always() }}
      uses: mxschmitt/action-tmate@v3
